apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: redis-namespace
spec:
  containers:
    - name: debug-container
      image: python:3.9  # Possui curl, ping e outras ferramentas
      command: ["sleep", "3600"]  # Mantém o pod rodando
      stdin: true
      tty: true
