apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-namespace
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes

  init-redis-cluster.sh: |
    #!/bin/bash
    set -e

    CONFIG="/usr/local/etc/redis/redis.conf"

    # Inicia Redis em background
    redis-server $CONFIG --daemonize yes
    sleep 10

    # Se for o primeiro pod, cria o cluster
    if [[ $(hostname) == "redis-cluster-0" ]]; then
      echo "Criando cluster Redis..."
      redis-cli --cluster create \
        redis-cluster-0.redis-cluster:6379 \
        redis-cluster-1.redis-cluster:6379 \
        redis-cluster-2.redis-cluster:6379 \
        redis-cluster-3.redis-cluster:6379 \
        redis-cluster-4.redis-cluster:6379 \
        redis-cluster-5.redis-cluster:6379 \
        --cluster-replicas 1 --cluster-yes
    fi

    # Para Redis em background e reinicia em foreground
    redis-cli shutdown
    exec redis-server $CONFIG
