apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-namespace
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-cluster
